export const FETCH_USERS_BEGGINING = 'FETCH_USERS_BEGGINING';
export const FETCH_USERS_RECEIVED = 'FETCH_USERS_RECEIVED';
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR';
export const SET_ACTUAL_USER = 'SET_ACTUAL_USER';
export const FETCH_POSTS_BEGGINING = 'FETCH_POSTS_BEGGINING';
export const FETCH_POSTS_RECEIVED = 'FETCH_POSTS_RECEIVED';
export const FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR';
